cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    administrador:
      client_code: '8236274157823465'
      email: administrador@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: administrador
      password: $2b$12$QJG/X7dhcVpvT6xwgBg3t.XryUCxOkFFMqAZsCln4HdoO86lIXlA6
      role: admin
    amaro:
      client_code: AMARO_LTDA
      email: amaro@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: amaro
      password: $2b$12$4Qd2mcrx1XojI/mz2uTFFeF4H32HxHI1triBFoXSQaeXO3qlyCVBe
      role: user
    astrazeneca:
      client_code: ASTRAZENECA_DO_BRASIL
      email: astrazeneca@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: astrazeneca
      password: $2b$12$g0/KpaqO/vMqxEW9Y4OdAeiCShml3inbIqPar83NYaQorngMPX4Ky
      role: user
    thiteste:
      client_code: ASTRAZENECA_DO_BRASIL
      email: thiagoteste@gmail.com
      failed_login_attempts: 1
      logged_in: false
      name: Thiago Teste
      password: $2b$12$I9EHF9ByzFlAWAw2vsV61.r7aGTNRU4zdVlTVtuKyGTa/92atsn7W
      role: user
form_labels:
  register:
    email: "Endere\xE7o de Email"
    name: Nome Completo
    password: Senha
    password_repeat: Repita a Senha
    register_button: Registrar
    username: "Nome de Usu\xE1rio"
pre-authorized:
  emails:
  - melsby@gmail.com
