cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    administrador2:
      client_code: 8236274157823465
      email: administrador2@gmail.com
      logged_in: true
      name: Thiago
      password: $2b$12$q2XO.jcGXUOT02Gz4F0/wu15KJnMr0prwVIPTct2IRaOYUSx5N9a6
      role: admin
    administrator:
      client_code: 15622
      email: Thiagocanon@gmail.com
      logged_in: true
      name: Thiago
      password: $2b$12$XPvBQQQ1p01payo4L4R8IOrUlumLIllTVGUJVi/q8XcCWId8aQ/gG
      role: admin
    adminteste:
      client_code: 8236274157823465
      email: teste@gmail.com
      failed_login_attempts: 1
      logged_in: true
      name: Admin Teste
      password: $2b$12$n8mvOMXIFwU8MMNHOv63s.rp7H1pzSvmibBVZeeFzatjdyjYHf8y2
      role: admin
    adminteste2:
      client_code: 8236274157823465
      email: adminteste2@gmail.com
      logged_in: true
      name: admin teste dois
      password: $2b$12$IGFK.JHRnSynbsmkYkipz.rgemQsI6QRQAey34RVbILiDpioY.b6u
      role: admin
    astrazenica:
      client_code: 31604
      email: astrazenica@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: Thiago
      password: $2b$12$UT8exZahWx2IEgi2CD4Uy.7070NS7lmGryGGKRwZ3cqclGJQUwSwG
      role: user
    dbaldwin:
      email: dbaldwin@gmail.com
      enterprise_code: null
      failed_login_attempts: 0
      logged_in: false
      name: David Baldwin
      password: $2b$12$E9/bCaN/r8sN/FV2l8NpgOgspUBAp7UAVU6BgsXJzp/pW8gQWCprC
      role: user
    fares:
      client_code: 33887
      email: fares@gmail.com
      failed_login_attempts: 2
      logged_in: false
      name: Thiago
      password: $2b$12$FcXUljpJYO2GofbYKvh6iuGoDgEy/Q60lrLofUWqoWkEHQrxX9p7a
      role: user
    jsmith:
      email: jsmith@gmail.com
      enterprise_code: null
      failed_login_attempts: 0
      logged_in: true
      name: John Smith
      password: $2b$12$iWlVOac3uujRvTrXDi6wructXftKmo/GyQd6SMu5FmyX306kH.yFO
      role: user
    novo_user:
      email: novo_user@gmail.com
      enterprise_code: null
      failed_login_attempts: 0
      logged_in: true
      name: Thiago
      password: $2b$12$ortrwcTOwwG2i1JzwYiOcedPbu7USNajeJRjTDToP6DJ98r32jDRu
      role: user
    raia:
      client_code: 11283
      email: raia@gmail.com
      failed_login_attempts: 1
      logged_in: true
      name: Thiago
      password: $2b$12$3kCu3SUYu5AuGkkwE8/AfeJLLnxI.sTioHL4xla04/rvx4u0YvFwe
      role: user
    rbriggs:
      email: rbriggs@gmail.com
      enterprise_code: null
      failed_login_attempts: 0
      logged_in: false
      name: Rebecca Briggs
      password: $2b$12$uNaTgvGPG9rMbzOJHYaPQePw0DUfp1qHBrSq6l4O304qani6pKFpm
      role: user
    rcouper:
      email: rcouper@gmail.com
      enterprise_code: null
      failed_login_attempts: 0
      logged_in: false
      name: Ross Couper
      password: $2b$12$Tir/PbHVmmnt5kgNxgOwMuxNIb2fv2pJ.q71TW8ekvbugCqkye4yu
      role: user
    scania:
      client_code: 31102
      email: scania@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: Thiago
      password: $2b$12$NFDYaJD0c4OmLx6S7KpWOe.NtAvI.l13hNvtegRi45fvUrh5ai2hy
      role: user
    surf:
      client_code: 30034
      email: surf@gmail.com
      logged_in: true
      name: Thiago
      password: $2b$12$L0A3BscExs9BAaJh4dVKKeB3JXh1nJ00B0BzyePOfc/MfUT9tCVaK
      role: user
    tadm:
      client_code: 8236274157823465
      email: tmedeiros@cusa.canon.com
      failed_login_attempts: 0
      logged_in: true
      name: Thiago Adm
      password: $2b$12$urIEG/pk5CGYNd1aZ5/8Muakb3pOSY8NLKm8nFsl17.XE0CihV6RW
      role: admin
    tauil:
      client_code: 31589
      email: taiul@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: Thiago
      password: $2b$12$nK5kHSn3h0JmsNWy2xfzQeDDNEoKs4caQfH082qFo4GvuPX0a7WfG
      role: admin
    thiagoteste:
      client_code: 8236274157823465
      email: emailteste@gmail.com
      logged_in: true
      name: Thiago
      password: $2b$12$fq2u6.Y9cS2SwsvQc1gnW.SgUQsAkoIsU5zzWCHREZrkv8DeyIXSW
      role: admin
    tjdft:
      client_code: 33544
      email: tjdft@gmail.com
      logged_in: true
      name: Thiago
      password: $2b$12$MpsxYH1FfoKvR4cGhNqBt.w.V6CtrTsJoeaXAPBnhmejpURIfFrBa
      role: user
    useradm:
      client_code: 8236274157823465
      email: adm@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: usuario administrador
      password: $2b$12$KAsH453NhKve.8BZgbobOOYutyqa.58WHs9lS2ULmg6ENviHt75ZC
      role: admin
    wdewe:
      email: wedw@ew.com
      enterprise_code: null
      failed_login_attempts: 0
      logged_in: false
      name: dwew
      password: $2b$12$QJBPc7PxaTTBVJ.3cl4KlOPPqYCWVfaHqkk2IsoGDExXhihKZLDgy
      role: user
    zelo:
      client_code: 15622
      email: zelo@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: zelo
      password: $2b$12$aw5tiGAOoQjx6dJsuWVJGux5oJmnqQjweuLAuNKUnHe6qCmejpzw2
      role: user
form_labels:
  register:
    email: "Endere\xE7o de Email"
    name: Nome Completo
    password: Senha
    password_repeat: Repita a Senha
    register_button: Registrar
    username: "Nome de Usu\xE1rio"
pre-authorized:
  emails:
  - melsby@gmail.com
